# Data Cleaning

Este notebook tem como objetivo realizar a limpeza e preparação dos dados utilizados no projeto.

Nesta etapa, serão tratados valores nulos, verificadas inconsistências e selecionadas as colunas mais relevantes para a análise do desempenho das equipes jogando em casa e fora de casa.

In [1]:
import pandas as pd

In [2]:
games = pd.read_csv('../data/raw/games.csv')
teams = pd.read_csv('../data/raw/teams.csv')

# Verificando Valores Nulos

Para mostrar quais colunas têm valores faltando.

In [3]:
games.isnull().sum()

GAME_DATE_EST        0
GAME_ID              0
GAME_STATUS_TEXT     0
HOME_TEAM_ID         0
VISITOR_TEAM_ID      0
SEASON               0
TEAM_ID_home         0
PTS_home            99
FG_PCT_home         99
FT_PCT_home         99
FG3_PCT_home        99
AST_home            99
REB_home            99
TEAM_ID_away         0
PTS_away            99
FG_PCT_away         99
FT_PCT_away         99
FG3_PCT_away        99
AST_away            99
REB_away            99
HOME_TEAM_WINS       0
dtype: int64

In [4]:
teams.isnull().sum()

LEAGUE_ID             0
TEAM_ID               0
MIN_YEAR              0
MAX_YEAR              0
ABBREVIATION          0
NICKNAME              0
YEARFOUNDED           0
CITY                  0
ARENA                 0
ARENACAPACITY         4
OWNER                 0
GENERALMANAGER        0
HEADCOACH             0
DLEAGUEAFFILIATION    0
dtype: int64

# Selecionando apenas as colunas importantes

In [5]:
games_clean = games[['GAME_DATE_EST', 'HOME_TEAM_ID', 'VISITOR_TEAM_ID', 'SEASON', 'PTS_home', 'PTS_away', 'HOME_TEAM_WINS']].copy()
teams_clean = teams[['TEAM_ID', 'ABBREVIATION', 'NICKNAME', 'CITY']].copy()

# Verificando novamente se há valores nulos nas colunas escolhidas

In [6]:
games_clean.isnull().sum()

GAME_DATE_EST       0
HOME_TEAM_ID        0
VISITOR_TEAM_ID     0
SEASON              0
PTS_home           99
PTS_away           99
HOME_TEAM_WINS      0
dtype: int64

In [7]:
teams_clean.isnull().sum()

TEAM_ID         0
ABBREVIATION    0
NICKNAME        0
CITY            0
dtype: int64

# Removendo linhas com dados ausentes relevantes

In [8]:
games_clean = games_clean.dropna()
teams_clean = teams_clean.dropna()

## Verificação de duplicatas

A verificação de duplicatas será feita com cautela, pois em datasets esportivos pode haver registros que parecem repetidos, mas representam informações relevantes.

No dataset de jogos, a remoção de duplicatas só será realizada caso seja confirmado que se trata da mesma partida repetida sem diferenças relevantes.

In [9]:
games_clean.duplicated().sum()

np.int64(29)

In [10]:
teams_clean.duplicated().sum()

np.int64(0)

In [11]:
games_clean[games_clean.duplicated(keep=False)].sort_values(by=['HOME_TEAM_ID', 'VISITOR_TEAM_ID', 'GAME_DATE_EST'])

,GAME_DATE_EST,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,PTS_home,PTS_away,HOME_TEAM_WINS
2536,2020-12-25,1610612738,1610612751,2020,95.0,123.0,0
3126,2020-12-25,1610612738,1610612751,2020,95.0,123.0,0
2499,2020-12-29,1610612739,1610612752,2020,86.0,95.0,0
3109,2020-12-29,1610612739,1610612752,2020,86.0,95.0,0
2517,2020-12-27,1610612740,1610612759,2020,98.0,95.0,1
3117,2020-12-27,1610612740,1610612759,2020,98.0,95.0,1
2545,2020-12-23,1610612741,1610612737,2020,104.0,124.0,0
3129,2020-12-23,1610612741,1610612737,2020,104.0,124.0,0
2521,2020-12-27,1610612741,1610612744,2020,128.0,129.0,0
3119,2020-12-27,1610612741,1610612744,2020,128.0,129.0,0
2512,2020-12-28,1610612743,1610612745,2020,124.0,111.0,1
3115,2020-12-28,1610612743,1610612745,2020,124.0,111.0,1
2483,2021-01-01,1610612743,1610612756,2020,103.0,106.0,0
3104,2021-01-01,1610612743,1610612756,2020,103.0,106.0,0
2489,2020-12-31,1610612745,1610612758,2020,122.0,119.0,1
3106,2020-12-31,1610612745,1610612758,2020,122.0,119.0,1
2504,2020-12-29,1610612748,1610612749,2020,97.0,144.0,0
3111,2020-12-29,1610612748,1610612749,2020,97.0,144.0,0
2535,2020-12-25,1610612749,1610612744,2020,138.0,99.0,1
3125,2020-12-25,1610612749,1610612744,2020,138.0,99.0,1
2547,2020-12-23,1610612750,1610612765,2020,111.0,101.0,1
3130,2020-12-23,1610612750,1610612765,2020,111.0,101.0,1
2494,2020-12-30,1610612751,1610612737,2020,145.0,141.0,1
3108,2020-12-30,1610612751,1610612737,2020,145.0,141.0,1
2479,2021-01-01,1610612751,1610612737,2020,96.0,114.0,0
3103,2021-01-01,1610612751,1610612737,2020,96.0,114.0,0
2510,2020-12-28,1610612751,1610612763,2020,111.0,116.0,0
3114,2020-12-28,1610612751,1610612763,2020,111.0,116.0,0
2520,2020-12-27,1610612754,1610612738,2020,108.0,107.0,1
3118,2020-12-27,1610612754,1610612738,2020,108.0,107.0,1
2540,2020-12-23,1610612754,1610612752,2020,121.0,107.0,1
3127,2020-12-23,1610612754,1610612752,2020,121.0,107.0,1
2502,2020-12-29,1610612755,1610612761,2020,100.0,93.0,1
3110,2020-12-29,1610612755,1610612761,2020,100.0,93.0,1
2542,2020-12-23,1610612755,1610612764,2020,113.0,107.0,1
3128,2020-12-23,1610612755,1610612764,2020,113.0,107.0,1
2506,2020-12-29,1610612756,1610612740,2020,111.0,86.0,1
3112,2020-12-29,1610612756,1610612740,2020,111.0,86.0,1
2508,2020-12-29,1610612758,1610612743,2020,125.0,115.0,1
3113,2020-12-29,1610612758,1610612743,2020,125.0,115.0,1
2533,2020-12-26,1610612758,1610612756,2020,106.0,103.0,1
3124,2020-12-26,1610612758,1610612756,2020,106.0,103.0,1
2530,2020-12-26,1610612759,1610612761,2020,119.0,114.0,1
3122,2020-12-26,1610612759,1610612761,2020,119.0,114.0,1
2491,2020-12-31,1610612760,1610612740,2020,80.0,113.0,0
3107,2020-12-31,1610612760,1610612740,2020,80.0,113.0,0
2484,2021-01-01,1610612762,1610612746,2020,106.0,100.0,1
3105,2021-01-01,1610612762,1610612746,2020,106.0,100.0,1
2531,2020-12-26,1610612762,1610612750,2020,111.0,116.0,0
3123,2020-12-26,1610612762,1610612750,2020,111.0,116.0,0
2524,2020-12-26,1610612763,1610612737,2020,112.0,122.0,0
3120,2020-12-26,1610612763,1610612737,2020,112.0,122.0,0
2477,2021-01-01,1610612765,1610612738,2020,96.0,93.0,1
3102,2021-01-01,1610612765,1610612738,2020,96.0,93.0,1
2515,2020-12-27,1610612766,1610612751,2020,106.0,104.0,1
3116,2020-12-27,1610612766,1610612751,2020,106.0,104.0,1
2525,2020-12-26,1610612766,1610612760,2020,107.0,109.0,0
3121,2020-12-26,1610612766,1610612760,2020,107.0,109.0,0

In [12]:
games_clean = games_clean.drop_duplicates()

# Verificando tipos de dados

In [13]:
games_clean.info()

<class 'pandas.DataFrame'>
Index: 26523 entries, 0 to 26650
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   GAME_DATE_EST    26523 non-null  str
 1   HOME_TEAM_ID     26523 non-null  int64
 2   VISITOR_TEAM_ID  26523 non-null  int64
 3   SEASON           26523 non-null  int64
 4   PTS_home         26523 non-null  float64
 5   PTS_away         26523 non-null  float64
 6   HOME_TEAM_WINS   26523 non-null  int64
dtypes: float64(2), int64(4), str(1)
memory usage: 1.6 MB

In [14]:
teams_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   TEAM_ID       30 non-null     int64
 1   ABBREVIATION  30 non-null     str
 2   NICKNAME      30 non-null     str
 3   CITY          30 non-null     str
dtypes: int64(1), str(3)
memory usage: 1.1 KB

# Convertendo data

In [15]:
games_clean['GAME_DATE_EST'] = pd.to_datetime(games_clean['GAME_DATE_EST'])

# Visualizando resultado da limpeza

In [16]:
games_clean.head()

,GAME_DATE_EST,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,PTS_home,PTS_away,HOME_TEAM_WINS
0,2022-12-22,1610612740,1610612759,2022,126.0,117.0,1
1,2022-12-22,1610612762,1610612764,2022,120.0,112.0,1
2,2022-12-21,1610612739,1610612749,2022,114.0,106.0,1
3,2022-12-21,1610612755,1610612765,2022,113.0,93.0,1
4,2022-12-21,1610612737,1610612741,2022,108.0,110.0,0

In [17]:
teams_clean.head()

      TEAM_ID ABBREVIATION   NICKNAME         CITY
0  1610612737          ATL      Hawks      Atlanta
1  1610612738          BOS    Celtics       Boston
2  1610612740          NOP   Pelicans  New Orleans
3  1610612741          CHI      Bulls      Chicago
4  1610612742          DAL  Mavericks       Dallas

# Salvando os dados tratados

In [18]:
games_clean.to_csv('../data/processed/clean_games.csv', index=False)
teams_clean.to_csv('../data/processed/clean_teams.csv', index=False)

## Resultado da limpeza

Foram selecionadas apenas as colunas mais relevantes para a análise do projeto.

Também foram tratados valores nulos, removidas possíveis duplicatas e ajustados os tipos de dados, deixando a base pronta para a próxima etapa: análise exploratória.